[build-system]
requires = [
    "setuptools",  # needed pre-install
    "numpy",  # needed pre-install
    "pip"  # to make pip accessible during installation
]
build-backend = "setuptools.build_meta"
