"01":
  adata_output_dir: "pipeline_output/adatas/"
  log_file: "pipeline_output/logs/01_log.txt"
  overwrite_log: True

"02":
  adata_input_dir: "pipeline_output/adatas/"
  adata_output_dir: "pipeline_output/adatas/"
  figure_dir: "pipeline_output/figures/02_QC/"
  log_file: "pipeline_output/logs/02_log.txt"
  overwrite_log: True

"03":
  adata_input_dir: "pipeline_output/adatas/"
  adata_output_dir: "pipeline_output/adatas/"
  figure_dir: "pipeline_output/figures/03_batch_correction/"
  log_file: "pipeline_output/logs/03_log.txt"
  overwrite_log: True

"04":
  adata_input_dir: "pipeline_output/adatas/"
  adata_output_dir: "pipeline_output/adatas/"
  figure_dir: "pipeline_output/figures/04_clustering/"
  log_file: "pipeline_output/logs/04_log.txt"
  overwrite_log: True

"05":
  adata_input_dir: "pipeline_output/adatas/"
  adata_output_dir: "pipeline_output/adatas/"
  figure_dir: "pipeline_output/figures/05_markers/"
  log_file: "pipeline_output/logs/05_log.txt"
  overwrite_log: True

"06":
  adata_input_dir: "pipeline_output/adatas/"
  adata_output_dir: "pipeline_output/adatas/"
  figure_dir: "pipeline_output/figures/06_prop_analysis/"
  log_file: "pipeline_output/logs/06_log.txt"
  overwrite_log: True